spring:
  application:
    name: itemify-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/application-dev
    username: application
    password: application
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true